### ISSUE TITLE
log.SetLogger(...) was never called

### ISSUE THREAD

**Issue by MegaByte875** [vesoft-inc/nebula-operator#311]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed:
goroutine 635 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
        sigs.k8s.io/controller-runtime@v0.15.2/pkg/log/log.go:59 +0xbd
sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0xc000407e40, {0x249e50e, 0x9})
        sigs.k8s.io/controller-runtime@v0.15.2/pkg/log/deleg.go:147 +0x4c
github.com/go-logr/logr.Logger.WithName(...)
        github.com/go-logr/logr@v1.2.4/logr.go:336
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).getLogger.func1()
        sigs.k8s.io/controller-runtime@v0.15.2/pkg/webhook/admission/webhook.go:182 +0x63
sync.(*Once).doSlow(0x0?, 0xc0004f6050?)
        sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        sync/once.go:65
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).getLogger(0xc0004f6c30?, 0xc0018c5500?)
        sigs.k8s.io/controller-runtime@v0.15.2/pkg/webhook/admission/webhook.go:180 +0x53
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc0004f6c30, {0x7faa32cd8488?, 0xc000816960}, 0xc00179f300)
        sigs.k8s.io/controller-runtime@v0.15.2/pkg/webhook/admission/http.go:96 +0xc34
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1({0x7faa32cd8488, 0xc000816960}, 0x29af500?)
        github.com/prometheus/client_golang@v1.15.1/prometheus/promhttp/instrument_server.go:60 +0xd4
net/http.HandlerFunc.ServeHTTP(0x29af550?, {0x7faa32cd8488?, 0xc000816960?}, 0xc00177b828?)
        net/http/server.go:2122 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x29af550?, 0xc00052a2a0?}, 0xc00179f300)
        github.com/prometheus/client_golang@v1.15.1/prometheus/promhttp/instrument_server.go:147 +0xc5
net/http.HandlerFunc.ServeHTTP(0x70d485?, {0x29af550?, 0xc00052a2a0?}, 0x7faa5a36ca68?)
        net/http/server.go:2122 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x29af550, 0xc00052a2a0}, 0xc00179f300)
        github.com/prometheus/client_golang@v1.15.1/prometheus/promhttp/instrument_server.go:109 +0xc7
net/http.HandlerFunc.ServeHTTP(0xc00052a2a0?, {0x29af550?, 0xc00052a2a0?}, 0x24a01bf?)
        net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0017c53cd?, {0x29af550, 0xc00052a2a0}, 0xc00179f300)
        net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0x299e010?}, {0x29af550, 0xc00052a2a0}, 0xc00179f300)
        net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc00095b8c0, {0x29b0628, 0xc0006fc660})
        net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        net/http/server.go:3089 +0x5ed

**Your Environments (__required__)**

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by MegaByte875** [comment]
https://github.com/vesoft-inc/nebula-operator/pull/323
